### ISSUE TITLE
Question new influxdb version

### ISSUE THREAD

**Issue by evilmumi** [c1328/ahoy-iobroker-influx-grafana#1]
Hi, is there a plan / idea  / etc to move it to the new influxdb version with flux?

**Comment by c1328** [comment]
Hi! There is currently no plan to switch to influxdb v2.x but I would expect that ioBroker can read/write v2.x databases:
![image](https://user-images.githubusercontent.com/112856305/215132570-00f4450d-4177-425f-adfa-4ddfeeb8fe43.png)
And grafana can also connect to v2.x databases so it should be possible to replace v1.x influxdb in my report by a v2.x

**Comment by c1328** [comment]
Sometimes plans change quicker than expected. Please check first draft based on influxdb2: https://github.com/c1328/ahoy-iobroker-influx-grafana/blob/main/ioB-PV-Power-Ahoy_Influx2_rev0.9.json
Feedback is appriciated

**Comment by evilmumi** [comment]
Thanks. And i found out that i posted below the wrong project. I only use mqtt,telegraf, grafana no iobroker.
so i had to edit it for me I think

**Comment by evilmumi** [comment]
do you have a new version?

**Comment by c1328** [comment]
I just published my current version. Feel free to use it :-)
